name: Update VK Photos

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python fetch_vk.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Добавляем файл
          git add data.json

          # Проверяем изменения
          if git diff --cached --quiet; then
            echo "🚫 Нет изменений в data.json — пуш не требуется"
          else
            echo "📝 Есть изменения в data.json — делаем коммит"
            cat data.json
            git commit -m "Update data.json with latest VK photos"

            # Меняем remote URL на с токеном GH_PAT
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

            # Выполняем пуш
            git push origin main
          fi
