name: Update VK Photos

on:
  # Запуск каждый день в полночь по UTC
  schedule:
    - cron: '0 0 * * *'
  # Возможность запуска вручную через интерфейс GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python fetch_vk.py

      - name: Show data.json content
        run: |
          if [ -f data.json ]; then
            echo "🔍 Содержимое data.json:"
            cat data.json
          else
            echo "❌ Файл data.json не найден"
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Добавляем файл в индекс
          git add data.json

          # Проверяем изменения
          if git diff --cached --quiet; then
            echo "🚫 Нет изменений в data.json — пуш не требуется"
          else
            echo "📝 Есть изменения в data.json — делаем коммит"
            git commit -m "Update data.json with latest VK photos"

            # Используем GH_PAT для пуши
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

            # Выполняем пуш в main
            git push origin main
          fi
